apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo
  namespace: demo
data:
  cm-name: megaultrademo
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cmref-demo
  namespace: demo
spec:
  containers:
    - image: alpine:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo \"I’m using var: $CM_VAR\"; sleep 10; done"]
      name: alpine-cmdemo
      env:
        - name: CM_VAR
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: cm-name
