apiVersion: v1
kind: Pod
metadata:
  name: pod-envvar-demo
  namespace: demo
spec:
  containers:
  - image: debian
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $CM_VAR; sleep 10; done"]
    name: debian-envvar-demo
    env:
    - name: CM_VAR
      value: "I'm over 9000"
