apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mount-demo
  namespace: demo
data:
  title-name: megaultrademo
  somerandomapp.properties: |
    name=megaApp
    version=1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cmmount-demo
  namespace: demo
spec:
  containers:
    - image: alpine
      name: alpine-cmmount
      command: ["bin/sh"]
      args: ["-c", "while true; do echo \"I'm using CM mount\"; sleep 20; done"]
      volumeMounts:
        - mountPath: /config
          name: demo-config-volume
          readOnly: true
  volumes:
    - name: demo-config-volume
      configMap:
        name: cm-mount-demo
