apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo
  namespace: demo
data:
  cm-name: megaultrademo
  somerandomapp.properties: |
    name=megaApp
    version=1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: demo
spec:
  containers:
  -  image: alpine
     name: pod-demo-alpine
     command: ["l", "-l", "/config"]
     volumeMounts:
     - mountPath: /config
       name: demo-config-volume
       readOnly: true
   volumes:
     - name: demo-config-volume
       configMap:
         name: cm-demo