apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl-demo
  namespace: demo
  labels:
    app: nginx-depl-demo
spec:
  replicas: 3	# Hvor mange replicas
  selector:		# Hvilke Pods ReplicaSet skal styre
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80