apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-nginx-demo
  namespace: demo
  labels:
    app: nginx
spec:
  replicas: 3 # Hvor mange replicas
  selector:   # Hvilke Pods ReplicaSet skal styre
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - containerPort: 80
