apiVersion: v1
kind: Pod
metadata:
  name: pod-limits-demo
  namespace: demo
spec:
  containers:
  - image: vish/stress
    name: pod-limits-alpine
    args:
      - -cpus
      - "2"
    resources:
      limits:
        cpu: 1
        memory: "200Mi"
      requests:
        cpu: 0.5
        memory: "100Mi"
