apiVersion: v1
kind: Pod
metadata:
  name: pod-startup-demo
  namespace: demo
spec:
  containers:
  - image: registry.k8s.io/liveness
    name: pod-liveness
    args:
      - /server
    startupProbe:
      httpGet:
        path: /healthz
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /healthz
        port: liveness-port
      failureThreshold: 1
      periodSeconds: 10
