apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness-demo
  namespace: demo
spec:
  containers:
  -  image: busybox
     name: pod-liveness-bb
     args:
       - /bin/sh
       - -c
       - touch /tmp/healthy; sleep 30; rm –f /tmp/healthy; sleep 600
     livenessProbe:
       exec:
         command: [«cat», «/tmp/healthy»]
       initialDelaySeconds: 5  # vent 5 sec før første probe
       periodSeconds: 5        # utfør en probe hvert 5. sec
