apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
  namespace: demo
data:
  user: cm9vdA==
  password: cm9vdA==
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-demo
  namespace: demo
spec:
  containers:
    - image: mysql
      name: pod-mysql-demo
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: password
