apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: test
spec:
  containers:
  - image: busybox:latest
    name: pod-demo-bb
    command: |
      while true; do echo "Hi, I'm PodMan!" sleep 2; done