apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: depl-pvc-cfgvol
  namespace: demo
data:
  filegen.sh: |
    #!/bin/sh

    while true
    do
      touch /data/newfile-$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)
      sleep 10
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-pvc-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wl-volume
  template:
    metadata:
      labels:
        app: wl-volume
    spec:
      containers:
        - image: debian
          name: debian-pvc-demo
          command: ["/bin/sh", "-c"]
          args: ["/ex/filegen.sh"]
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /ex
              name: runscript
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-demo
        - name: runscript
          configMap:
            name: depl-pvc-cfgvol
            defaultMode: 0777
