apiVersion: v1
kind: Service
metadata:
  name: sfs-demo-svc
  namespace: demo
spec:
  selector:
    app: sfs-nginx
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: sfs-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sfs-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi
