apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: demo
spec:
  selector:
    name: nginx
  type: NodePort
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30088
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:	# StatefulSet spesifikt for PVC’er som Pods skal referere til
  - metadata:
      name: www
    spec:
      accessModes: [«ReadWriteOnce»]
      storageClassName: local-storage
      resources:
        requests:
          storage: 1Gi
